FORMAT: 1A

# Unitwise API

Unitwise is a RESTful JSON API for converting and performing calculations on physical quantities or units of measure.

# Units [/units.json?q={query}]

## Search Available [GET]

+ Parameters
    + query (required, string) ... The term to search for.
+ Response 200 (application/json)
    + Body
    
            [["km","kilometer"]]


# Conversions [/conversions.json]

Conversions have a `source` measurement, a `target` unit, and a `result` measurement. The `source` and `target` have both a `value` (Numeric) and a `unit` (String).

## Create [POST]

Provide a `source` measurement and a `target` unit to recieve a `result` measurement.

+ Request (application/json)

        {
            "source": {
                "value": 3,
                "unit": "foot"
            },
            "target": "yard"
        }

+ Response 200 (application/json)

        {
            "source": {
                "value": 3,
                "unit": "foot"
            },
            "target": "yard"
            "result": {
                "value": 1,
                "unit": "yard"
            }
        }

